#!/bin/bash

if [ ! -v TTY_ENABLED ]; then
	export TTY_ENABLED="-it"
fi
docker run --rm ${TTY_ENABLED} -u $(id -u):$(id -g) -v /tmp:/tmp -v /home:/home -v /opt/$PFX/usr:/opt/$PFX/usr -w $PWD amigadev/docker-base "$@"
